# Generated by Django 3.0.3 on 2020-04-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
